### ISSUE TITLE
Buscar donde encontrar datos de jueces que no matchearon

### ISSUE THREAD

**Issue by mgutierrezc** [mgutierrezc/peru-amag-stats#4]
@pmalca, en los archivos `apellido_nombre_merge.xlsx` y `nombre_apellido_merge.xlsx` de la carpeta [Cases Outcomes](https://drive.google.com/drive/u/1/folders/1JnPamAdB2HzUaqytwRtgp835CdzcB7hA) estan los nombres de todos los jueces del experimento para los que encontramos datos online. 

La idea es buscar alguna pagina web donde esten todos los jueces que no son parte de estos dos archivos y que esten en `Clean_Full_Data12.dta` (variable Nombres + Apellidos). Ademas, tienen que ser Jueces que vean casos civiles.

Esta pagina puede ser [la que te pase antes](https://cej.pj.gob.pe/cej/forms/busquedaform.html) u otra

**Comment by mgutierrezc** [comment]
Para los jueces de exp_participants_list.csv que no hayan matcheado, buscar en [Consulta tu juez](https://sap.pj.gob.pe/casillero-digital-web/#/conoce-tu-juez) una muestra aleatoria de 20 de ellos.

Si se encuentran expedientes suyos para 2022, buscar los expediente en CEJ

**Comment by mgutierrezc** [comment]
@pmalca como vamos con esta tarea?

**Comment by pmalca** [comment]
De la revisión de 20 jueces, estos si aparecen en consulta tu juez. Asimismo, los expedientes que aparecen en la sección "sentido de fallo", sirven para acceder a ellos vía CEJ

**Comment by mgutierrezc** [comment]
Gracias! Todavia no cierres jeje. Pregunta, sus expedientes salen disponibles para 2022? De ser asi, podrias postear un ejemplo?

**Comment by pmalca** [comment]
![Imagen de WhatsApp 2023-08-21 a las 20 58 05](https://github.com/mgutierrezc/peru-amag-stats/assets/115379356/3f5fd3a3-5418-4599-8427-c84f35445667)

**Comment by pmalca** [comment]
![image](https://github.com/mgutierrezc/peru-amag-stats/assets/115379356/ecf2125e-5f5b-4cb9-8956-e788109c3e09)

**Comment by mgutierrezc** [comment]
Pero ese expediente es de 2018. No ha resuelto ningun expediente de 2022?

**Comment by mgutierrezc** [comment]
Para mañana, no para hoy. 

Mira, encontre esto: 

Casillero dice que ella se hizo cargo de este doc
![image](https://github.com/mgutierrezc/peru-amag-stats/assets/43623521/c7ff7551-38ba-46dd-a0d1-a6ebb6d1c5e9)

Pero CEJ da el nombre de otra jueza. Que crees que haya pasado? 
![image](https://github.com/mgutierrezc/peru-amag-stats/assets/43623521/062fff50-6120-4ddb-9652-15aba5040c56)
